# Start a postgresql server
version: "3.9"
services:
  postgres:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # app:
  #   image: nestjs-api
  #   build: .
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?connect_timeout=10"
  #     DIRECT_URL: "postgres://postgres:postgres@postgres:5432/postgres?connect_timeout=10"

volumes:
  postgres-data:
