# Start a postgresql server
version: '3.9'
services:
  postgres:
    image: postgres:14.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - 5050:80
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  # app:
  #   image: nestjs-api
  #   build: .
  #   ports:
  #     - 4000:4000
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: "postgres://postgres:postgres@postgres:5432/postgres?connect_timeout=10"

volumes:
  postgres-data:
  pgadmin-data:
